title: "Jordan Simpson"
description: "I am an aspiring Cybersecurity analyst building skills in threat hunting and security operations."
url: "https://www.simpsonjordan.com" #Your github url goes here
baseurl: "" 

author: "Jordan Simpson"
twitter:
  username:
social:
  name: ""
  links:
    - "https://twitter.com/yourusername"
    - "https://linkedin.com/in/yourusername"
    - "https://github.com/J0rdynh0"
    
remote_theme: realnamesareboring/jekyll-and-hire

plugins:
 - jekyll-remote-theme
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-feed    
